 # @package _global_
# This header make any parameters in these configs global.

defaults:
  - default
  - override /system: learnconf

train: false
weights: ${model_path}/${choices.data}${camus_labels:${data.labels}}-${choices.system}-${seed}.ckpt