# @package _global_
# This header make any parameters in these configs global.

defaults:
  - default
  - override /system: segmentation

name: ${choices.data}${camus_labels:${data.labels}}-${choices.system}-${seed}.ckpt
