# @package _global_
# This header make any parameters in these configs global.

defaults:
  - default
  - override /system: crisp/train

name: ${choices.data}${camus_labels:${data.labels}}-crisp-${seed}.ckpt

# my changes to verify hyperspace saving
#save_samples_name: ${choices.data}${camus_labels:${data.labels}}-crisp-${seed}-zbar.pt
#system:
#  save_samples: /home/zoayada1/intern_thesis_work/RMS_SampleFinder/depends/crisp/checkpoints/${seed}/${save_samples_name}
