# @package _global_
# This header make any parameters in these configs global.

defaults:
  - default
  - override /system: crisp/eval
  - override /data: hmc_qu

train: false
system:
  clip_ckpt: ${model_path}/camus-MYO-crisp-${seed}.ckpt
  samples_path: ${model_path}/camus-MYO-samples-4CH-seq-${seed}.pt
  num_samples: 150
  uncertainty_threshold: 0.3