
defaults:
  - _self_
  - vital_default # This references default config from vital.config.vital_default.yaml
  - trainer: default
  - system: uncertainty
  - data: camus
  - logger: comet/offline
  - callbacks:
      - early_stopping
      - model_checkpoint
  - override system/module: unet

# Set comet project name and workspace
logger:
  project_name: crisp-miccai2022
  workspace: thierryjudge

seed: 55

trainer:
  max_epochs: 1000

callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss
    patience: 100
    mode: min
