# @package _global_
# This header make any parameters in these configs global.

defaults:
  - lung_default
  - override /system: softmax

train: false
weights: ${model_path}/${choices.data}-segmentation-DA${data.da}-${seed}.ckpt
