# @package _global_
# This header make any parameters in these configs global.

defaults:
  - lung_default
  - override /system: mcdropout

train: false
weights: ${model_path}/${choices.data}-${choices.system}${frac:${system.module.dropout}}-DA${data.da}-${seed}.ckpt