# @package _global_
# This header make any parameters in these configs global.

defaults:
  - default
  - override /system: mcdropout
  - override /data: lung

system:
  module:
    dropout: 0.5

test: false
name: ${choices.data}-${choices.system}${frac:${system.module.dropout}}-DA${data.da}-${seed}.ckpt